## Example 1

The code below simulates forward propagation of a 2x2 artificial neural network (ANN). In this example, we use the following notation:
The inputs into the ANN are represented by a 2x1 column matrix called $I$. The weights between the input later and the next layer are represented by a matrix called $W$.

$$
I = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix}
$$


$$
W = \begin{pmatrix} w_{1,1} ~~ w_{2,1} \\ w_{1,2}  ~~ w_{2,2} \end{pmatrix}
$$

In the square matrix $W$, the first row represents the weights coming into the hidden layer. The first column represents the weights coming out of the input layer.

In [1]:
# Import numpy library and define a sigmoid function that we will use later.
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
# Create the input matrix I and the matrix W of weights
I = np.array([[1.0], [0.5]])
W = np.array([[0.9, 0.3], [0.2, 0.8]])

# Print the matrices to see what they look like
print(np.matrix(W))
print(np.matrix(I))

[[0.9 0.3]
 [0.2 0.8]]
[[1. ]
 [0.5]]


In [5]:
# First calculation: Combine inputs with weights to get the input values coming into layer H.
H_in = np.dot(W, I)
H_in

array([[1.05],
       [0.6 ]])

In [6]:
# Second calculation: Apply the sigmoid function to H_in to get the output signal from layer H.
H_out = sigmoid(H_in)
H_out

array([[0.7407749 ],
       [0.64565631]])

## Example 2

Now modify the code above to work out what the ouput values, represented by `H_out` will be with the following input matrix and weights. You answer should be a single 2x1 column matrix.

$$
I = \begin{pmatrix} 0.7 \\ 0.2 \end{pmatrix}
$$

$$
W = \begin{pmatrix} 0.6 ~~ 0.5 \\ 0.4  ~~ 0.9 \end{pmatrix}
$$

In [ ]:
# Type your code here


## Example 3

In the example below, we are dealing with a 3x3 network. The steps are the same as in the simpler example, but there are more layers and more calculations, so the matrices are bigger. Here is an explantory list of the matrices used below.

I
W_ih
W_oh
H_in
H_out
O

In [9]:
W_ih = np.array([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])
W_ho = np.array([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])

In [16]:
I = np.zeros(3)
I = np.array([[0.9],[0.1], [0.8]])

In [17]:
H_in = np.dot(W_ih, I)
H_in

array([[1.16],
       [0.42],
       [0.62]])

In [18]:
H_out = sigmoid(H_in)
H_out

array([[0.76133271],
       [0.60348325],
       [0.65021855]])

In [19]:
O = np.dot(W_ho, H_out)

In [20]:
O

array([[1.12633184],
       [0.76509685],
       [0.76800603]])