# Python NumPy - Answers to Exercise 1

## Exercise 1

Let's use what we have learned to answer some more questions using a larger dataset.

The file "Denver_Daily_Temps_2021-25.csv" contains the daily high, low and average temperatures for Denver for the years 2021-2025, so from Jan 01 2021 to Dec 31 2025. The units are degrees celsius. These data are taken from the [Meteostat](https://meteostat.net/en/) website.

First, copy the file over from Github:

Copy this URL: https://raw.githubusercontent.com/guyfrancis/dat1001/refs/heads/main/Denver_Daily_Temps_2021-25.csv
Use File > Open from URL... and paste in the URL above.
Before you run any Python code, take a look at the CSV file. You'll see that there are 11 columns. We will use columns 1, 2, 3, which cover average temp (tavg), minimum temperate (tmin), maximum temperature (tmax) as in the example above. Remember you will need to convert the temperature units to degrees Fahrenheit and use the `np.T` method to transpose the data.

See if you can answer the questions below. 
1. What was the highest temperature during the 5-year period in deg F and when did it occur?
2. What was the lowest temperature during the 5-year period in deg F and when did it occur?
3. What was the average temperature over the 5-year period?
4. What day in the 5-year period had the smallest temperature range, and what was it, in deg F?
5. (Challenge) Find the maximum temperature range in each year 2021, 2022, 2023, 2024 and 2025. Do these all occur roughly around the same time of year?

In [1]:
# Load Denver temperature data and set print options
import numpy as np
file = "Denver_Daily_Temps_2021-25.csv"
den_temps = np.loadtxt(file, usecols=(1, 2, 3), skiprows=1, delimiter=",")
np.set_printoptions(floatmode='fixed', precision=1)
den_temps = den_temps.T
print(den_temps)

[[-1.5 -2.0  1.1 ... -3.0  0.7  4.6]
 [-5.2 -7.7 -4.6 ... -9.5 -6.6 -4.8]
 [ 3.5  4.9  8.2 ...  4.4  8.8 15.2]]


In [2]:
# Convert to deg F and split into 3 separate arrays
den_temps = 9/5*den_temps + 32
tavg = den_temps[0]
tmin = den_temps[1]
tmax = den_temps[2]

In [3]:
# Maximum temp over 5 years
max_temp = tmax.max()
max_temp_days = np.where(tmax == max_temp)
print(f"Max temp was {max_temp:.2f} on day {max_temp_days[0][0]}.")

Max temp was 99.14 on day 165.


In [4]:
# Minimum temp over 5 years
min_temp = tmin.min()
min_temp_days = np.where(tmin == min_temp)
print(f"Min temp was {min_temp:.2f} on day {min_temp_days[0][0]}.")

Min temp was -5.44 on day 1110.


In [5]:
# Average temp over 5 years
ave_temp = tavg.mean()
print(f"Average temp over 5 years was {ave_temp:.2f}.")

Average temp over 5 years was 52.15.


In [6]:
# Finding max daily temperature range
trange = tmax - tmin
print(f"Maximum daily temp range was {trange.max():.2f}")
when_max_range = np.where(trange == trange.max())
print(f"This occurred on day {when_max_range[0][0]}, which was day {when_max_range[0][0] - 365*3 - 366} of year 2025.")

Maximum daily temp range was 41.22
This occurred on day 1481, which was day 20 of year 2025.


In [7]:
# Challenge: finding max temperature range in each year
# As the output indicates, this tends to occur early in the year during winter (but not always)
yr = 2021
yr_start = 0
while yr <= 2025:
    print("Year:", yr)
    yr_end = yr_start+365
    if yr==2024:
        yr_end+=1
    print(f"Max temperature range in {yr} was {trange[yr_start:yr_end].max():.2f} def F.")
    when = np.where(trange[yr_start:yr_end]==trange[yr_start:yr_end].max())[0][0]
    print("This occurred on day:", when)
    yr+=1
    yr_start = yr_end

Year: 2021
Max temperature range in 2021 was 34.92 def F.
This occurred on day: 172
Year: 2022
Max temperature range in 2022 was 39.06 def F.
This occurred on day: 57
Year: 2023
Max temperature range in 2023 was 37.26 def F.
This occurred on day: 47
Year: 2024
Max temperature range in 2024 was 34.02 def F.
This occurred on day: 102
Year: 2025
Max temperature range in 2025 was 41.22 def F.
This occurred on day: 20
