# Python NumPy

The `numpy` library (pronounced num - pie) is a library of numerical functions and tools that are useful in scientific computing, data science and machine learning. In particular, the library has a data structure called `array` which is really useful.

To import the library, you use the following code:
```
import numpy as np
```
The `as` keyword allows us to give the library an alias (in thise case `np`) which just means we don't have to type as many letters when we refer to it.

Let's import it first. We will then use some of its features to look at some local historical weather data.

In [2]:
# Import numpy library
import numpy as np

## Looking at Weather Data

The file "Denver_Daily_Temps_2025.csv" contains the daily high, low and average temperatures for Denver for 2025.The units are degrees celsius. These data are taken from the [Meteostat](https://meteostat.net/en/) website.

First, copy the file over from Github if you haven't already:

- Copy this URL: https://raw.githubusercontent.com/guyfrancis/dat1001/refs/heads/main/Denver_Daily_Temps_2025.csv
- Use **File > Open from URL...** and paste in the URL above.
- Before you run any Python code, take a look at the CSV file. You'll see that there are four columns: day, average temp (tavg), minimum temperate (tmin) and maximum temperature (tmax).

We are going to use numpy arrays to help us answer some basic questions about the temperature last year:
1. What was the highest temperature in deg F?
2. What was the lowest temperature in deg F?
3. What was the average temperature in deg F over the whole year?
4. What the daily temperature range (max - min) in deg F for each day of the year?
5. What was the maximum temperature range on any day and on what day did this occur?

We want answers in deg F, so we will need to convert the units for our data from deg C to deg F.


In [18]:
# Load Denver temperature data and set print options
file = "Denver_Daily_Temps_2025.csv"
den_temps_25 = np.loadtxt(file, usecols=(1, 2, 3), skiprows=1, delimiter=",")
np.set_printoptions(floatmode='fixed', precision=1)
print(den_temps_25)

[[-3.5 -7.8  1.5]
 [ 0.0 -6.1  6.7]
 [ 0.6 -5.1  7.8]
 ...
 [-3.0 -9.5  4.4]
 [ 0.7 -6.6  8.8]
 [ 4.6 -4.8 15.2]]


### Reshape data
The data are currently organized into 365 rows of 1 x 3 arrays. Each row corresponds to one day. We are going to reshape these data into 3 rows of 365 days, with each row representing one type of temperature measurement: average, min and max. To do this we can **transpose** the data to reshape it.

In [19]:
print("Original shape of data:", den_temps_25.shape)
den_temps_25 = den_temps_25.T
# den_temps_25 = np.reshape(den_temps_25, (365,3))
print("New shape of data:", den_temps_25.shape)
print(den_temps_25)

Original shape of data: (365, 3)
New shape of data: (3, 365)
[[-3.5  0.0  0.6 ... -3.0  0.7  4.6]
 [-7.8 -6.1 -5.1 ... -9.5 -6.6 -4.8]
 [ 1.5  6.7  7.8 ...  4.4  8.8 15.2]]


### Convert units to deg F

To convert degrees Celsius to degrees Farenheit, we need to multiply every value by `9/5` and add `32`. With numpy arrays, this can be done in one line.

In [20]:
# Change units to deg F from deg C
den_temps_25 = 9/5*den_temps_25 + 32
print(den_temps_25)

[[25.7 32.0 33.1 ... 26.6 33.3 40.3]
 [18.0 21.0 22.8 ... 14.9 20.1 23.4]
 [34.7 44.1 46.0 ... 39.9 47.8 59.4]]


### Create separate arrays for average, min and max
To make answering the questions easy and to make the code readable, we will create separate one-dimensional arrays for each temperature measurement.

In [22]:
tavg = den_temps_25[0]
tmin = den_temps_25[1]
tmax = den_temps_25[2]
print(tavg.shape, tmin.shape, tmax.shape)

(365,) (365,) (365,)


Now we can answer the first three questions with a couple of lines of code.

In [36]:
# Find highest temperature for year
print(f"Highest temp in 2025 was {tmax.max():.1f} deg F.")

# Find the lowest temperature of the year
print(f"Lowest temp in 2025 was {tmin.min():.1f} deg F.")

# Find average temperature for the year by averaging the daily average temperatures
print(f"Average temp in 2025 was {tavg.mean():.1f} deg F.")

Highest temp in 2025 was 96.8 deg F.
Lowest temp in 2025 was -3.6 deg F.
Average temp in 2025 was 53.1 deg F.


### Daily Temperature Ranges
We can create a new numpy array giving the daily temperature range by calculating `tmax - tmin` for each day in the year. We can then find the maximum temperature range and we can use the `numpy.where()` method to find what day this was.

In [40]:
# Create numpy array of daily temperature ranges
trange = tmax - tmin

# Find the greatest temperature range
print(f"Max daily temp range in 2025 was {trange.max():.1f} deg F.")

# Find what day this was on. Numpy.where returns a tuple for each sub-array containing a list of all locations where the value occurs, so to get
# just the first day when this temp range occurs we need to use the [0][0] index.
max_range_day = np.where(trange == trange.max())[0][0]
print(f"This happened on day {max_range_day} of the year.")

Max daily temp range in 2025 was 41.2 deg F.
This happened on day 20 of the year.


## Exercise 1

Let's use what we have learned to answer some more questions using a larger dataset.

The file "Denver_Daily_Temps_2021-25.csv" contains the daily high, low and average temperatures for Denver for the years 2021-2025, so from Jan 01 2021 to Dec 31 2025. The units are degrees celsius. These data are taken from the [Meteostat](https://meteostat.net/en/) website.

First, copy the file over from Github:

Copy this URL: https://raw.githubusercontent.com/guyfrancis/dat1001/refs/heads/main/Denver_Daily_Temps_2021-25.csv
Use File > Open from URL... and paste in the URL above.
Before you run any Python code, take a look at the CSV file. You'll see that there are 11 columns. We used columns 1, 2, 3, 8 and 10, which cover average temp (tavg), minimum temperate (tmin), maximum temperature (tmax), windspeed (in km/h) and pressure (in millibars). Remember you will need to convert the temperature units to degrees Fahrenheit.

See if you can answer the questions below. 
1. What was the highest temperature during the 5-year period in deg F and when did it occur?
2. What was the lowest temperature in deg F and when did it occur?
3. What was the average temperature over the 5-year period?
4. What day in the 5-year period had the greatest temperature range, and what was it, in deg F?
5. What was the average windspeed in 2021 in mph?

Here are a couple more challenging questions:

6. Find the maximum temperature range in each year 2021, 2022, 2023, 2024 and 2025. Do these all occur around the same time of year?
7. Is there a particular month of the year that is windier on average than other months, based on the data for these 5 years?

In [ ]:
# Type your code here
# Add more code cells as needed


## Exercise 2

For this exercise, you can go straight to the [Meteostat](https://meteostat.net/en/) website to find some weather data for a time period and location of your choosing. download the CSV and use some Python code to analyze and describe your data along the lines of what we have done above.